---
- name: Mise à jour de l'OS
  dnf:
    name: "*"
    state: latest

- name: Installation de curl
  dnf:
    name: 'curl'
    state: latest

#########################################################
########### Désactivation du SELinux ####################
#########################################################

- name: Désactivé SELinux au prochain redemarrage
  selinux:
    state: disabled

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false

###############################################################################################
#### Activez le masquage transparent et facilitez le trafic de réseau local                  ##  
#### extensible virtuel (VxLAN) pour la communication entre les pods Kubernetes du cluster.  ##                     
###############################################################################################

- name: activé transparent masquerading 
  modprobe:
    name: br_netfilter
    state: present

################################################################################
#### Vous devrez également activer la mascarade IP au niveau du pare-feu. ######   
################################################################################

- name: activé IP masquerade at the firewall.
  firewalld:
    masquerade: 'True'
    state: enabled
    permanent: yes

- name: rechargement du service firewalld
  systemd:
    name: firewalld
    state: reloaded

##################################################################################
########## Définissez les paquets pontés pour traverser les règles iptables. #####
##################################################################################

- name: Execute cat 
  shell: | 
      cat > /etc/sysctl.d/k8s.conf << EOF
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF

########################################################      
###### Ensuite, chargez les nouvelles règles ###########
########################################################

- name: execution du systctl --system
  shell: sysctl --system
