Vagrant.configure("2") do |config|
    config.vm.define "kubmaster" do |kub|
      kub.vm.box = "generic/centos8"
      kub.vm.hostname = 'kubmaster'
      kub.vm.provision "docker"
      kub.vm.box_url = "generic/centos8"
  
      kub.vm.network :private_network, ip: "192.168.12.101"
  
      kub.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--name", "kubmaster"]
        v.customize ["modifyvm", :id, "--cpus", "2"]
      end
    end
  
    config.vm.define "kubnode1" do |kubnode|
      kubnode.vm.box = "generic/centos8"
      kubnode.vm.hostname = 'kubnode1'
      kubnode.vm.provision "docker"
      kubnode.vm.box_url = "generic/centos8"
  
      kubnode.vm.network :private_network, ip: "192.168.12.102"
  
      kubnode.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--name", "kubnode"]
        v.customize ["modifyvm", :id, "--cpus", "2"]
      end
    end
    config.vm.define "kubnode2" do |kubnode|
      kubnode.vm.box = "generic/centos8"
      kubnode.vm.hostname = 'kubnode2'
      kubnode.vm.provision "docker"
      kubnode.vm.box_url = "generic/centos8"
  
      kubnode.vm.network :private_network, ip: "192.168.12.103"
  
      kubnode.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--name", "kubnode2"]
        v.customize ["modifyvm", :id, "--cpus", "2"]
      end
    end
  end